### ISSUE TITLE
Print exceptions when in development or test environments

### ISSUE THREAD

**Issue by silaspedrosa** [rhino-project/rhino-project#307]
During tests, if a request unexpectedly fails with a 500, there's no way to tell what went wrong. We need this code in `app/controllers/concerns/rhino/error_handling.rb#handle_uncaught_error`:

```ruby
if Rails.env.development? || Rails.env.test?
  puts exception.backtrace.join("\n")
  puts exception.message
end
```

**Comment by jprosevear** [comment]
I'm a little puzzled because it should be recorded in the logger still, but will check it out
